Build:
    # parameters for the build
    Distro:
        - Ubuntu

    Platform:
        - D02
        - D03
DISTRO:
    D02:
        - Ubuntu: Ubuntu_ARM64.tar.gz
        - Fedora: Fedora_ARM64.tar.gz
        - OpenSuse: OpenSuse_ARM64.tar.gz
        - Debian: Debian_ARM64.tar.gz
        - CentOS: CentOS_ARM64.tar.gz
        - Rancher: Rancher_ARM64.tar.gz
    D03:
        - Ubuntu: Ubuntu_ARM64.tar.gz
        - Fedora: Fedora_ARM64.tar.gz
        - OpenSuse: OpenSuse_ARM64.tar.gz
        - Debian: Debian_ARM64.tar.gz
        - CentOS: CentOS_ARM64.tar.gz
        - Rancher: Rancher_ARM64.tar.gz
    D05:
        - CentOS: CentOS_ARM64.tar.gz
        - Ubuntu: Ubuntu_ARM64.tar.gz

# the dictionary for the board and arch mapping
Arch:
    d05: arm64
    d03: arm64
    d02: arm64

# for lava connection
#    TOKEN: p53l26plbujbqaicsrkw0i1u3xu5qawxlx3imr41w3eiwg1y79jxtjkx209p2kccsc1obzy279c7ruydhskzotdlf6s3me0wb87o0rf71m0sehetlje9p0cr0dorkhf8
LAVA:
    USER: htsat
    HOST: 192.168.1.108
    TOKEN: 0p9a29zs4rq15xyaaw9eza9sa1hsdb8axx4p9fankh6j0304wrla08w9n7s9qghn2m8bnofcolbrng0sy0zzef7awwt6hjnajhmnoq5aj0ufxm4mqt7629d3fskcnm75
    lavaserver: http://192.168.1.108/RPC2/
    lavastream: /anonymous/admin/
    lavauser: admin

# for lava job parameter
Jenkins:
    Boot: boot
    App:
        - WEEKLY_TESTING
        - TEST

# for kernelci access
Ftpinfo:
    ftpserver: http://192.168.1.108:8083
    FTP_DIR : /fileserver/open-estuary
